USE RAILWAY;
GO
CREATE PROCEDURE VIEW_EMPLOYEES
AS
BEGIN
SELECT * FROM Employee
END
GO

CREATE PROCEDURE VIEW_TRIPS
AS
BEGIN
SELECT * FROM TRIP
END
GO

CREATE PROCEDURE VIEW_TRAINS
AS
BEGIN
SELECT * FROM TRAIN
END
GO

CREATE PROCEDURE VIEW_STATIONS
AS
BEGIN
SELECT * FROM STATION
END
GO

CREATE PROCEDURE VIEW_SUPPLIERS
AS
BEGIN
SELECT * FROM SUPPLIER
END
GO

CREATE PROCEDURE VIEW_SPARE_PARTS
AS
BEGIN
SELECT * FROM SPARE_PART
END
GO

CREATE PROCEDURE CHANGE_TRAIN_MAINTENANCE_DATE @New_Date DATE,@Train_Number INT
AS
BEGIN
UPDATE TRAIN SET Maintenance_Day = @New_Date
WHERE Train_Number = @Train_Number
END
GO

CREATE PROCEDURE ADD_TRIP @Trip_Num INT , @Deprt_Time DATETIME, @Arr_Time DATETIME
, @Eco_Ticket_Price INT, @Buss_Ticket_Price INT, @Buss_No INT, @Eco_No INT
, @Train_No INT
AS
BEGIN
INSERT INTO TRIP (Trip_Number, Departure_Time, Arrival_Time, Economic_Ticket_Price
, Business_Ticket_Price, Business, Economic, Train_Number)
VALUES
(@Trip_Num,@Deprt_Time,@Arr_Time,@Eco_Ticket_Price, @Buss_Ticket_Price, @Buss_No,@Eco_No
,@Train_No)
END
GO

CREATE PROCEDURE REMOVE_TRIP @Trip_Num INT 
AS
BEGIN
DELETE FROM TRIP 
WHERE Trip_Number = @Trip_Num
END
GO



CREATE PROCEDURE VIEW_SPARE_PARTS_IN_STATION @Station_No INT
AS
BEGIN
SELECT Part_Number,Quantity
FROM INVENTORY
WHERE Station_Number = @Station_No
END
GO


CREATE PROCEDURE DEC_SPARE_PARTS @Station_No INT, @Part_No INT, @Amount INT
AS
BEGIN
UPDATE INVENTORY
SET Quantity = Quantity - @Amount
WHERE Station_Number = @Station_No AND Part_Number = @Part_No
END
GO


CREATE PROCEDURE ORDER_SPARE_PARTS @Part_No INT, @Amount INT, @SSN BIGINT ,@RequestID INT
AS
BEGIN
INSERT INTO REQUEST (Request_ID, E_SSN, Part_Number, Quantity, [Status] )
VALUES (@RequestID,@SSN,  @Part_No, @Amount, 'Pending Approval')
END
GO


CREATE PROCEDURE INSERT_EMPLOYEE @Fname VARCHAR(50), @Minit VARCHAR(50), @Lname VARCHAR(50), @SSN BIGINT,
								@Sex VARCHAR(50),@DOB DATE, @Phone_Number BIGINT, @Salary INT,
								@Manager_SSN BIGINT, @Station VARCHAR
AS
BEGIN
INSERT INTO EMPLOYEE (Fname,Minit,Lname,E_SSN,Sex,DOB,Phone_Number,Salary,Manager_SSN)
VALUES(@Fname,@Minit,@Lname,@SSN,@Sex,@DOB,@Phone_Number,@Salary,@Manager_SSN)
END
GO

CREATE PROCEDURE CHECK_EMPLOYEE_BY_SSN @SSN BIGINT
AS
BEGIN
SELECT COUNT(*)
FROM EMPLOYEE
WHERE E_SSN=@SSN
END
GO

CREATE PROCEDURE REMOVE_EMPLOYEE @SSN BIGINT
AS
BEGIN
DELETE FROM EMPLOYEE
WHERE E_SSN = @SSN
END
GO